
import java.io.File;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hdm
 */
public class ConfigJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ConfigJFrame
     */
    public ConfigJFrame() {
        initComponents();
        /* ラジオボタングループ化 */
        ButtonGroup group0 = new ButtonGroup();
        group0.add(jRadioButtonMenuItemUTF8);
        group0.add(jRadioButtonMenuItemSJIS);
    }

    public int getMojiCode() {
        if (jRadioButtonMenuItemUTF8.isSelected()) {
            return 0;
        }else {
            return 1;
        }
    }
    public void setMojiCode(int idx) {
        if (idx == 0) {
            jRadioButtonMenuItemUTF8.setSelected(true);
        }else {
            jRadioButtonMenuItemSJIS.setSelected(true);
        }
    }
    public void setText(String[] str) {
        jTextFieldCSV.setText(str[0]);
        jTextFieldDB.setText(str[1]);
        jTextField1.setText(str[2]);
        jTextField2.setText(str[3]);
        jTextField3.setText(str[4]);
        jTextField4.setText(str[5]);
        jTextField5.setText("ファイル名");
    }
    
    public void getText(String[] str) {
        str[0] = jTextFieldCSV.getText();
        str[1] = jTextFieldDB.getText();
        str[2] = jTextField1.getText();
        str[3] = jTextField2.getText();
        str[4] = jTextField3.getText();
        str[5] = jTextField4.getText();
        str[6] = jTextField5.getText();
        str[7] = "データ本文";
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogCSV = new javax.swing.JDialog();
        jFileChooser1 = new javax.swing.JFileChooser();
        jSplitPane1 = new javax.swing.JSplitPane();
        jSplitPane2 = new javax.swing.JSplitPane();
        jSplitPane3 = new javax.swing.JSplitPane();
        jSplitPane4 = new javax.swing.JSplitPane();
        jSplitPane5 = new javax.swing.JSplitPane();
        jSplitPane6 = new javax.swing.JSplitPane();
        jSplitPane7 = new javax.swing.JSplitPane();
        jSplitPane14 = new javax.swing.JSplitPane();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jSplitPaneInst = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jButtonInst = new javax.swing.JButton();
        jSplitPane13 = new javax.swing.JSplitPane();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jSplitPane12 = new javax.swing.JSplitPane();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jSplitPane11 = new javax.swing.JSplitPane();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jSplitPane10 = new javax.swing.JSplitPane();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSplitPane9 = new javax.swing.JSplitPane();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldDB = new javax.swing.JTextField();
        jSplitPane8 = new javax.swing.JSplitPane();
        jLabel1 = new javax.swing.JLabel();
        jSplitPaneFile = new javax.swing.JSplitPane();
        jButtonFile = new javax.swing.JButton();
        jTextFieldCSV = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemHtmlFrame = new javax.swing.JMenuItem();
        jMenuItemLibreWriter = new javax.swing.JMenuItem();
        jMenuItemMail = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jRadioButtonMenuItemUTF8 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItemSJIS = new javax.swing.JRadioButtonMenuItem();

        jDialogCSV.setTitle("CSVを選択");
        jDialogCSV.setAlwaysOnTop(true);
        jDialogCSV.setBounds(new java.awt.Rectangle(100, 100, 500, 400));

        javax.swing.GroupLayout jDialogCSVLayout = new javax.swing.GroupLayout(jDialogCSV.getContentPane());
        jDialogCSV.getContentPane().setLayout(jDialogCSVLayout);
        jDialogCSVLayout.setHorizontalGroup(
            jDialogCSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFileChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialogCSVLayout.setVerticalGroup(
            jDialogCSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFileChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setTitle("環境設定");
        setBounds(new java.awt.Rectangle(100, 100, 0, 0));

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jSplitPane1ComponentResized(evt);
            }
        });

        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jSplitPane3.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jSplitPane4.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jSplitPane5.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jSplitPane6.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jSplitPane7.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jSplitPane14.setDividerLocation(140);

        jLabel7.setText("項目名５");
        jLabel7.setMaximumSize(new java.awt.Dimension(150, 0));
        jLabel7.setPreferredSize(new java.awt.Dimension(120, 13));
        jSplitPane14.setLeftComponent(jLabel7);

        jTextField5.setEditable(false);
        jTextField5.setText("jTextField5");
        jSplitPane14.setRightComponent(jTextField5);

        jSplitPane7.setTopComponent(jSplitPane14);

        jPanel1.setPreferredSize(new java.awt.Dimension(250, 23));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        jSplitPaneInst.setLeftComponent(jPanel1);

        jButtonInst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/checkbox.png"))); // NOI18N
        jButtonInst.setText("登録");
        jButtonInst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInstActionPerformed(evt);
            }
        });
        jSplitPaneInst.setRightComponent(jButtonInst);

        jSplitPane7.setRightComponent(jSplitPaneInst);

        jSplitPane6.setBottomComponent(jSplitPane7);

        jSplitPane13.setDividerLocation(140);

        jLabel6.setText("項目名４");
        jLabel6.setMaximumSize(new java.awt.Dimension(150, 0));
        jLabel6.setPreferredSize(new java.awt.Dimension(120, 13));
        jSplitPane13.setLeftComponent(jLabel6);

        jTextField4.setText("jTextField4");
        jSplitPane13.setRightComponent(jTextField4);

        jSplitPane6.setLeftComponent(jSplitPane13);

        jSplitPane5.setBottomComponent(jSplitPane6);

        jSplitPane12.setDividerLocation(140);

        jLabel5.setText("項目名３");
        jLabel5.setMaximumSize(new java.awt.Dimension(150, 0));
        jLabel5.setPreferredSize(new java.awt.Dimension(120, 13));
        jSplitPane12.setLeftComponent(jLabel5);

        jTextField3.setText("jTextField3");
        jSplitPane12.setRightComponent(jTextField3);

        jSplitPane5.setLeftComponent(jSplitPane12);

        jSplitPane4.setBottomComponent(jSplitPane5);

        jSplitPane11.setDividerLocation(140);

        jLabel4.setText("項目名２");
        jLabel4.setMaximumSize(new java.awt.Dimension(150, 0));
        jLabel4.setPreferredSize(new java.awt.Dimension(120, 13));
        jSplitPane11.setLeftComponent(jLabel4);

        jTextField2.setText("jTextField2");
        jSplitPane11.setRightComponent(jTextField2);

        jSplitPane4.setLeftComponent(jSplitPane11);

        jSplitPane3.setBottomComponent(jSplitPane4);

        jSplitPane10.setDividerLocation(140);
        jSplitPane10.setMinimumSize(new java.awt.Dimension(150, 21));

        jLabel3.setText("項目名１");
        jLabel3.setMaximumSize(new java.awt.Dimension(150, 0));
        jLabel3.setPreferredSize(new java.awt.Dimension(120, 13));
        jSplitPane10.setLeftComponent(jLabel3);

        jTextField1.setText("jTextField1");
        jSplitPane10.setRightComponent(jTextField1);

        jSplitPane3.setLeftComponent(jSplitPane10);

        jSplitPane2.setBottomComponent(jSplitPane3);

        jSplitPane9.setDividerLocation(140);

        jLabel2.setText("データベースタイトル");
        jLabel2.setMaximumSize(new java.awt.Dimension(150, 0));
        jLabel2.setPreferredSize(new java.awt.Dimension(120, 13));
        jSplitPane9.setLeftComponent(jLabel2);

        jTextFieldDB.setText("jTextFieldDB");
        jTextFieldDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDBActionPerformed(evt);
            }
        });
        jSplitPane9.setRightComponent(jTextFieldDB);

        jSplitPane2.setLeftComponent(jSplitPane9);

        jSplitPane1.setBottomComponent(jSplitPane2);

        jSplitPane8.setDividerLocation(140);

        jLabel1.setText("ファイル名");
        jLabel1.setMaximumSize(new java.awt.Dimension(150, 0));
        jLabel1.setMinimumSize(new java.awt.Dimension(116, 13));
        jLabel1.setPreferredSize(new java.awt.Dimension(120, 13));
        jSplitPane8.setLeftComponent(jLabel1);

        jButtonFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/document-open.png"))); // NOI18N
        jButtonFile.setText("参照");
        jButtonFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFileActionPerformed(evt);
            }
        });
        jSplitPaneFile.setRightComponent(jButtonFile);

        jTextFieldCSV.setText("jTextFieldCSV");
        jTextFieldCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCSVActionPerformed(evt);
            }
        });
        jSplitPaneFile.setLeftComponent(jTextFieldCSV);

        jSplitPane8.setRightComponent(jSplitPaneFile);

        jSplitPane1.setLeftComponent(jSplitPane8);

        jMenu1.setText("ファイル");

        jMenuItem1.setText("新規作成");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        jMenuItemHtmlFrame.setText("HTML作成(CSSFrame)");
        jMenuItemHtmlFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHtmlFrameActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemHtmlFrame);

        jMenuItemLibreWriter.setText("LibreOffice文書作成");
        jMenuItemLibreWriter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLibreWriterActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemLibreWriter);

        jMenuItemMail.setText("メール送信設定");
        jMenuItemMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMailActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemMail);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("文字コード");

        jRadioButtonMenuItemUTF8.setSelected(true);
        jRadioButtonMenuItemUTF8.setText("UTF-8");
        jRadioButtonMenuItemUTF8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItemUTF8ActionPerformed(evt);
            }
        });
        jMenu2.add(jRadioButtonMenuItemUTF8);

        jRadioButtonMenuItemSJIS.setSelected(true);
        jRadioButtonMenuItemSJIS.setText("Shift-JIS");
        jMenu2.add(jRadioButtonMenuItemSJIS);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFileActionPerformed
        String[] str = {"","","","","","","","","","","",""};
        card.ConfFrm.getText(str);
        File filePath = new File(str[0]);
        String path = "";
        if (filePath.exists()) {
            path = filePath.getAbsolutePath();
        }else {
            //ファイル名指定しないで参照ボタンを押した場合、
            //初期表示ディレクトリがHomeDirになってしまうのをカレントディレクトリに変更 Ver 2.0.0.2         2015.5.16
            //path = filePath.getParent();
            if (str[0].equals("")) {
                //カレント
                path = new File(".").getAbsolutePath();
            }else {
                //ファイルのパスの親ディレクトリ
                path = filePath.getParent();
            }
        }
        //ファイル選択ダイアログでファイル名・フォルダ名の変更モードを抑止　Ver 2.0.0.2     2013.5.17
        UIManager.put("FileChooser.readOnly", Boolean.TRUE);
        JFileChooser filechooser = new JFileChooser(path);
        //ファイル選択ダイアログでcsvファイルのみ指定：Ver 2.0.0.2  2013.5.17
        CsvFilter filter = new CsvFilter();
        filechooser.addChoosableFileFilter(filter);
        filechooser.setFileFilter(filter);
        //ファイルダイアログ呼び出し
        if (filechooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = filechooser.getSelectedFile();
            jTextFieldCSV.setText(file.getPath());
            //ファイルが存在しない場合は新規作成モード
            if (!file.exists()) {
                int ret = JOptionPane.showConfirmDialog(this, "新規にデータベースを作成しますか？");
                if (ret == JOptionPane.YES_OPTION) {
                    for (int i = 0; i < card.ArrStr.length; i++) {
                        card.ArrStr[i].clear();
                    }
                    card.CardFrm.initList();
                    return;
                }else {
                    //No及び取り消しが押された場合、データは触らない
                    return;
                }
            }
        }
        //ファイルの内容を画面に反映
        card.readCSV();
    }//GEN-LAST:event_jButtonFileActionPerformed

    private void jSplitPane1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jSplitPane1ComponentResized
        jSplitPaneFile.setDividerLocation(jSplitPaneFile.getSize().width - jButtonFile.getMinimumSize().width - 20);
        jSplitPaneInst.setDividerLocation(jSplitPaneInst.getSize().width - jButtonInst.getMinimumSize().width - 20);
    }//GEN-LAST:event_jSplitPane1ComponentResized

    private void jTextFieldDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDBActionPerformed

    private void jButtonInstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInstActionPerformed
        card.writeCSV(true, this);
    }//GEN-LAST:event_jButtonInstActionPerformed

    private void jRadioButtonMenuItemUTF8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItemUTF8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMenuItemUTF8ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //新規作成
        for (int i = 0; i < 6; i++) {
            card.ArrStr[i] = new ArrayList();
            card.ArrStr[i].clear();
            //初期化
            card.initFrame();
            card.CardFrm.initList();
            card.CardFrm.initListTitle();
            //Card画面の更新
            String[] str = {"","","","","","","","","","",""};
            card.CardFrm.setConf(str);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jTextFieldCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCSVActionPerformed
        String[] str = {"","","","","","","","","","","",""};
        card.ConfFrm.getText(str);
        File filePath = new File(str[0]);
        if (filePath.exists()) {
            //ファイルの内容を画面に反映
            card.readCSV();
        }
    }//GEN-LAST:event_jTextFieldCSVActionPerformed

    private void jMenuItemMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMailActionPerformed
        card.MailFrm.setVisible(true);
    }//GEN-LAST:event_jMenuItemMailActionPerformed

    private void jMenuItemLibreWriterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLibreWriterActionPerformed
        // LibreOffice Writer 連携
        LibreWriter lib = new LibreWriter();
        lib.makeWiterFile();
    }//GEN-LAST:event_jMenuItemLibreWriterActionPerformed

    private void jMenuItemHtmlFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHtmlFrameActionPerformed
        card.writeHtmlCSSFrame();
    }//GEN-LAST:event_jMenuItemHtmlFrameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfigJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfigJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfigJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfigJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfigJFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFile;
    private javax.swing.JButton jButtonInst;
    private javax.swing.JDialog jDialogCSV;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemHtmlFrame;
    private javax.swing.JMenuItem jMenuItemLibreWriter;
    private javax.swing.JMenuItem jMenuItemMail;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemSJIS;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemUTF8;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane10;
    private javax.swing.JSplitPane jSplitPane11;
    private javax.swing.JSplitPane jSplitPane12;
    private javax.swing.JSplitPane jSplitPane13;
    private javax.swing.JSplitPane jSplitPane14;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JSplitPane jSplitPane4;
    private javax.swing.JSplitPane jSplitPane5;
    private javax.swing.JSplitPane jSplitPane6;
    private javax.swing.JSplitPane jSplitPane7;
    private javax.swing.JSplitPane jSplitPane8;
    private javax.swing.JSplitPane jSplitPane9;
    private javax.swing.JSplitPane jSplitPaneFile;
    private javax.swing.JSplitPane jSplitPaneInst;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextFieldCSV;
    private javax.swing.JTextField jTextFieldDB;
    // End of variables declaration//GEN-END:variables
}
